#! /bin/bash

if [[ -x /usr/bin/curl ]] || [[ -x /bin/curl ]]; then
	curl https://raw.githubusercontent.com/m-GDEV/ifetch/master/ifetch -o /tmp/ifetch
else
	echo "Error Occured. Please create an issue on Github."
	exit 1
fi


echo -e "\n\nInstalling program to /usr/local/bin"
sudo cp /tmp/ifetch /usr/local/bin
sudo chmod +x /usr/local/bin/ifetch

echo "ifetch installed!"
ifetch
